name: Execução de Testes Mobile

on:
  push:
    branches: ["main", "feature/*"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: macos-latest 
    defaults:
      run:
        working-directory: mobile-automation

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar Dependências
        run: npm install

      - name: Baixar Aplicativo de Demonstração
        run: npm run download:demo-app

      # Essa action sobe o emulador Android, espera ele ficar pronto e roda o script npm test
      - name: Executar Testes E2E no Emulador Android
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: Nexus 6
          working-directory: mobile-automation
          script: npm test

      - name: Salvar Resultados do Allure (Artifact)
        uses: actions/upload-artifact@v4
        if: always() # Garante que vai salvar mesmo se algum teste falhar
        with:
          name: allure-results-mobile
          path: mobile-automation/allure-results/
          retention-days: 5